Fix doc entry for `corpus_iterable` in `train`
RaRe-Technologies/gensim pull request #2945
Opened 2020-09-15 13:51 UTC by svenski

Fix doc entry for `corpus_iterable` in `train` (previously `sentences`).

2020-09-15 14:10 UTC, piskvorky requested changes
Thanks. One more little improvement, to clarify the motivation for "streamed input".

2020-09-15 14:10 UTC, piskvorky commented on gensim/models/fasttext.py
> +            The `corpus_iterable` iterable can be simply a list of lists of tokens, but for larger corpora,
```suggestion
            The `corpus_iterable` iterable can be simply a list of lists of tokens, but for larger corpora, to save RAM,
```

2020-09-15 15:02 UTC, svenski commented
Hmm, sorry, closing the commit was the wrong thing to do, re-opening!

2020-09-16 04:26 UTC, gojomo commented
Note that another in-progress PR #2944, in the course of fixing & cleaning up other things, has eliminated the `FastText.train()` method entirely in favor of simply sharing the implementation from `Word2Vec`.

I've made sure the `Word2Vec.train()` comment is similarly fixed in that PR via [this commit](https://github.com/RaRe-Technologies/gensim/pull/2944/commits/2387b5d9ac913506dabeecc5a423cab486d650b1), so this PR is now superfluous. 

Thanks for pointing this out, though, & please keep highlighting/proposing fixes for such errors!

2020-09-16 11:39 UTC, svenski commented
Ah, ok, no worries, thanks for letting me know.

2020-09-16 11:39 UTC, closed without merging