Add py39 wheels to travis/azure
RaRe-Technologies/gensim pull request #3058
Opened 2021-03-02 01:35 UTC by FredHappyface

Fixes #3056
Follows from #2966

## Summary 
Added py 3.9 build targets to travis/azure

2021-03-02 02:41 UTC, FredHappyface commented
Error building the nmslib wheel looking at the logs https://pypi.org/project/nmslib/

2021-03-04 05:19 UTC, mpenkov commented
Can you please conditionally disable Py3.9 wheel builds on Windows?

We'll have to handle them separately when the nsmlib wheels become available.

2021-03-05 01:52 UTC, mpenkov commented
@piskvorky WDYT?

Our options for Python 3.9 are:

1. Build wheels for non-Windows builds
2. Build nothing until nmslib wheels are available

@FredHappyface Please let me know if the above isn't a correct interpretation of the choice we need to make.

2021-03-05 02:03 UTC, FredHappyface commented
I would find it useful if we went ahead and built Windows wheels anyway as that is used in a pretty small component if I remember correctly?

But then again I would understand why you might be reluctant to do so. Of those two options I'd be most inclined to go with the former

2021-03-05 07:17 UTC, gojomo commented
Indeed if only one narrow function doesn't work, due to some other library not working, it could make sense to conditionally disable the test, make that a new open issue, and add a release-note that says: "NMS-related features don't work under Python 3.9 on Windows due to a problem with the [whatever] project, use an lower Python version if you need those functions."

2021-03-05 10:15 UTC, piskvorky commented
Yes. We definitely don't want to drop Windows builds on account of some marginal (in the sense of barely used in Gensim) external library.

2021-03-05 14:05 UTC, mpenkov commented
@FredHappyface Are you able to conditionally disable nmslib-dependent code such that Python3.9 builds for Windows succeed?

2021-03-05 18:12 UTC, FredHappyface commented
Manged to do that but now stymied by pyemd. Not sure if you want me to push what I've got or hold off for a bit?

2021-03-06 10:59 UTC, mpenkov commented
Thank you for taking this up. Can we handle PyEMD in the same way? I understand that the rabbit hole is getting deeper...

2021-03-06 12:37 UTC, FredHappyface commented
I'll certainly take a look. And yeah it is

I take it then that it's not essential to core functionality?

2021-03-06 12:53 UTC, FredHappyface commented
Further down the rabbit hole we go... https://github.com/ztane/python-Levenshtein/issues/63

2021-03-06 13:03 UTC, piskvorky commented
Jesus. What kind of apocalypse happened in Windows Py3.9?

2021-03-06 13:07 UTC, FredHappyface commented
No idea - a few things have been deprecated but not sure why it's destroyed so many extensions

2021-03-06 13:14 UTC, FredHappyface commented
Looks like we are getting the same error as in the upstream repos on my local machine. (I am certain that MS BuildTools is installed). I have no idea what is causing this

<details>
  <summary>Spoiler warning</summary>

  ```cmd
PS C:\Users\Dell\Documents\GitHub\gensim> tox -e py39-win
py39-win create: C:\Users\Dell\Documents\GitHub\gensim\.tox\py39-win
py39-win installdeps: pip>=19.1.1, .[test-win]
py39-win installed: atomicwrites==1.4.0,attrs==20.3.0,colorama==0.4.4,Cython==0.29.22,gensim @ file:///C:/Users/Dell/Documents/GitHub/gensim,iniconfig==1.1.1,mock==4.0.3,Morfessor==2.0.2a4,numpy==1.20.1,packaging==20.9,pluggy==0.13.1,py==1.10.0,pyparsing==2.4.7,pytest==6.2.2,scipy==1.6.1,smart-open==4.2.0,testfixtures==6.17.1,toml==0.10.2
py39-win run-test-pre: PYTHONHASHSEED='1'        
py39-win run-test: commands[0] | python --version
Python 3.9.2
py39-win run-test: commands[1] | pip --version
pip 21.0.1 from C:\Users\Dell\Documents\GitHub\gensim\.tox\py39-win\lib\site-packages\pip (python 3.9)
py39-win run-test: commands[2] | python setup.py build_ext --inplace
C:\Users\Dell\Documents\GitHub\gensim\.tox\py39-win\lib\site-packages\setuptools\dist.py:461: UserWarning: Normalizing '4.0.0beta' to '4.0.0b0'
  warnings.warn(tmpl.format(**locals()))
running build_ext
building 'gensim.models.word2vec_inner' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
ERROR: InvocationError for command 'C:\Users\Dell\Documents\GitHub\gensim\.tox\py39-win\Scripts\python.EXE' setup.py build_ext --inplace (exited with code 1)_________________________________________________________________________ summary __________________________________________________________________________
ERROR:   py39-win: commands failed
  ```
  
</details>

2021-03-06 14:37 UTC, FredHappyface commented
Ok managed to fix the bug I introduced to py3.8 testing 

And managed to skip tests relying on Levenshtein for py3.9

Happy for me to push this (and is there anyway to disable the tests as I'm assuming these pushes are beginning to use up your azure hours)

2021-03-07 19:52 UTC, FredHappyface commented
Think I've sorted this out now.

2021-03-09 01:04 UTC, mpenkov requested changes
Thank you for your effort and persistence in getting this to work.

I left you some minor comments. Please have a look and get back to me.

2021-03-09 01:07 UTC, FredHappyface commented on gensim/similarities/levenshtein.py
> +        raise ImportError("Levenshtein not installed. Please run `pip install Levenshtein`.")
Thanks, my bad there! Slight oversight. Will fix

2021-03-09 01:08 UTC, FredHappyface commented on gensim/test/test_similarities.py
> +        try:
I agree, this reads far better

2021-03-09 01:09 UTC, FredHappyface commented on setup.py
> +not_py39_win_testenv = [
Yeah that also makes far more sense. I'll make these changes tomorrow

2021-03-09 01:13 UTC, mpenkov commented on gensim/similarities/levenshtein.py
> +        raise ImportError("Levenshtein not installed. Please run `pip install Levenshtein`.")
BTW, I don't think we need this try-except here if we catch the import error in gensim.similarities.__init__.

2021-03-09 15:53 UTC, piskvorky commented
Of course! You're on a roll :)

Can you merge `develop` into this PR? There were some changes recently, like removing some of the dependencies such as `viz`. To avoid wasted effort & potential git conflicts.

2021-03-10 04:33 UTC, mpenkov commented on gensim/similarities/__init__.py
> +        "Install Levenhstein (e.g. `pip install Levenshtein`) to suppress this warning."
;)

```suggestion
        "Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning."
```

2021-03-10 12:37 UTC, FredHappyface commented on gensim/similarities/__init__.py
> +        "Install Levenhstein (e.g. `pip install Levenshtein`) to suppress this warning."
Blast! Missed that! 😅 Right today's job

2021-03-15 05:06 UTC, merged

2021-03-15 05:06 UTC, mpenkov commented
Merging. Good work @FredHappyface ! Thank you for your contribution.