Fix: Eliminate step parameter
RaRe-Technologies/gensim pull request #3176
Opened 2021-06-18 06:16 UTC by rock420

Fixes: #3158 
Eliminate the step parameter from the function `infer_vector()` and `similarity_unseen_docs()`.  (modification in the code and function documentation)
No other code/docs/examples using the outdated `step` parameter.

2021-06-18 06:32 UTC, piskvorky requested changes

2021-06-18 06:32 UTC, piskvorky commented on gensim/models/doc2vec.py
> +        For a more stable representation, increase the number of epochs to assert a stricket convergence.
```suggestion
        For a more stable representation, increase the number of epochs to assert a stricker convergence.
```

2021-06-18 07:14 UTC, rock420 commented on gensim/models/doc2vec.py
> +        For a more stable representation, increase the number of epochs to assert a stricket convergence.
Done the typo fix.

2021-06-18 16:06 UTC, gojomo commented
Looks good to me. 

Will raise new exceptions for user code using `steps` as parameter to `infer_vector()` or `similarity_unseen_document()` that was previously using the default silently. 

As the previous behavior (to both accept `steps` and to ignore it) was buggy, I think that's OK in a `4.1` minor or even `4.0.x` bugfix release, with proper mention in release notes – but other possible standards for what counts as a 'breaking change' might disagree.

2021-06-18 19:25 UTC, piskvorky approved these changes

2021-06-29 00:51 UTC, mpenkov approved these changes
Looks good. Thank you for your contribution!

2021-06-29 00:55 UTC, merged