fix the problem of loading old gensim model by new gensim model
RaRe-Technologies/gensim pull request #3359
Opened 2022-06-22 07:34 UTC by funasshi

# Problem
the model created by gensim 3.8.3 cannot be loaded by load function of gensim 4.2.0 and Attribute error occurs.

# How to solve 
import Vocab in word2vec.py

2022-06-22 08:03 UTC, piskvorky approved these changes

2022-08-21 15:21 UTC, mpenkov requested changes

2022-08-21 15:21 UTC, mpenkov commented on gensim/models/word2vec.py
> +from gensim.models.keyedvectors import KeyedVectors, pseudorandom_weak_vector, Vocab
Is this really enough? Can you please add a test that successfully loads an older gensim model?

2022-08-22 07:02 UTC, mpenkov commented on gensim/models/word2vec.py
> +from gensim.models.keyedvectors import KeyedVectors, pseudorandom_weak_vector, Vocab
Also, this import appears unused to flake8, so we should add a directive to ignore it.

2022-10-16 08:02 UTC, piskvorky requested changes

2022-10-16 08:02 UTC, piskvorky commented on gensim/models/word2vec.py
> +# This unused import is "somehow" required to fix #3357
Explain the reason clearly – this comments not helpful.

2022-10-16 13:56 UTC, piskvorky requested changes

2022-10-16 13:56 UTC, piskvorky commented on gensim/models/word2vec.py
> +#
No need for this blank line – the comment above relates directly to the line below.

2022-10-17 00:51 UTC, piskvorky approved these changes

2022-10-17 01:12 UTC, mpenkov commented
Not sure why the changes are causing tests to consistently fail. Will need to look into it later.

2022-12-07 02:50 UTC, mpenkov commented
Thank you @funasshi !

2022-12-07 02:50 UTC, merged