Closes #3362: Install issue poetry
RaRe-Technologies/gensim pull request #3363
Opened 2022-07-08 19:14 UTC by jaymegordo

Fixes https://github.com/RaRe-Technologies/gensim/issues/3362

2022-07-08 19:29 UTC, jaymegordo commented
Also will resolve #3225

2022-08-19 11:31 UTC, vladyslav-burylov commented
Hi Team, 

We also facing an issue with this: without this fix, gensim cannot be installed via poetry 1.2.
Any chance this can be reviewed and merged?

Appreciating your help in advance.

2022-08-21 13:23 UTC, mpenkov commented on setup.py
> +            __builtins__.__NUMPY_SETUP__ = False
This particular part appears to be for Python 2 - we don't need it, right?

2022-08-21 13:26 UTC, mpenkov requested changes

2022-08-21 13:26 UTC, mpenkov commented on setup.py
> +                print("Skipping numpy hack; if installation fails, try installing numpy first")
What exception can possibly get raised here?

Assuming that some exception can, then a explicit error message would be better:

```suggestion
                print("Skipping numpy hack; if gensim installation fails, try installing numpy first")
```

Also, may as well output the reason why the hack failed (what exception was caught) and a trace.

2022-12-03 15:34 UTC, merged